name: Generate RSS Digest

on:
  schedule:
    - cron: '30 11 * * *'  # Every day at 5:00 PM IST (11:30 AM UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate digest
      run: python generate_digest.py

    - name: Commit and push RSS feed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add watts-up-india-digest.xml
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git push