name: Generate Weekly Newsletter

on:
  schedule:
    - cron: '30 3 * * 5'  # 9 AM IST Friday
  workflow_dispatch:

jobs:
  weekly-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate digest
        run: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} python generate_digest.py

      - name: Commit and push digest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add watts-up-india-digest.xml
          git commit -m "Weekly digest update [auto]" || echo "No changes to commit"
          git push
