name: Generate RSS Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC / 11:30 IST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser requests beautifulsoup4 openai

      - name: Generate RSS Digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_digest.py
